require-license: false
require-known-license: false

allow:
  - MIT
  - BSD-3-Clause
  - BSD-2-Clause
  - Apache-2.0
  - ISC
  - 0BSD
  - CC0-1.0
  - Unlicense

deny:
  - GPL-3.0
  - AGPL-3.0

ignore-packages:
  - 'actions/*'
